### ISSUE TITLE
Bug: Initial pet display

### ISSUE THREAD

**Issue by pearlwalker** [jyi2cute/HW_Practicing_Software_Development#2]
"Age" doesn't display an age, it displays the name of the class

Also, the first value shouldn't be labeled "Key" if the second isn't labeled "Value", or the second shouldn't be labeled "Age" if the first isn't labeled "Name"

Proof:
<img width="298" alt="animal-shelter_bug_key-display" src="https://github.com/user-attachments/assets/bf2aadc5-a596-4c4c-8644-2dbd894f17c7">
<img width="428" alt="animal-shelter_bug_key-display_age-error" src="https://github.com/user-attachments/assets/a9c12f0c-9e97-4930-a971-2889dd8ec1a5">

**Comment by ShawnGHB** [comment]
This was just display code for checking if things were being accessed correctly, will remove after Demo Functions are complete. I have resolved the issue with Age not displaying an age by changing the dictionary value type to the Pet object itself. As opposed to <string, object>
