### ISSUE TITLE
Bug: Adoption "softlock"

### ISSUE THREAD

**Issue by pearlwalker** [jyi2cute/HW_Practicing_Software_Development#3]
You can successfully adopt a pet on the list, but
a. you can't go back to the "main menu"
b. you are still prompted to adopt a pet even if there are no pets remaining

Proof: 
https://github.com/user-attachments/assets/6e987c04-08bf-4f09-8a09-47f14a7f4881

**Comment by ShawnGHB** [comment]
Added in Check for the amount of Pets in the dictionary, and you can now go back to the main menu with Exit
