### ISSUE TITLE
WIP: Learn/Browse/Leave output

### ISSUE THREAD

**Issue by pearlwalker** [jyi2cute/HW_Practicing_Software_Development#4]
Learn: returns nothing
Browse: returns placeholder string
Leave: abruptly ends program

Learn could use some placeholder text. I also am not sure what the difference between "Learn" and "Browse" would be. The only information we have about the pets is their name/age/breed (at least with what's in place right now for pets being returned), so there's nothing to "Learn" about the pets that wouldn't come up in "Browse"

Proof:
https://github.com/user-attachments/assets/9b208a63-83ad-4082-8b96-7255d4e9b1dc

**Comment by ShawnGHB** [comment]
We agreed that Browse would return the name and one feature of our pets for a general overview, while our Learn function should list the entire object's value. Also Leave will say goodbye once user exits

**Comment by ShawnGHB** [comment]
I've updated our Browse, Leave, and Learn Code so it's now only awaiting inspect. I will comment it out for more clarity, but all changes should resolve this issue.
