### ISSUE TITLE
Bug: Only the first letter of user input matters

### ISSUE THREAD

**Issue by pearlwalker** [jyi2cute/HW_Practicing_Software_Development#5]
The program only looks at the first letter of whatever the user inputs, not capitalization/the rest of the string. 

Proof:

**Animal** being processed as **Adopt**: https://github.com/user-attachments/assets/7f562680-677b-4cc3-9f85-179392663512
**Romp** being process as **Return**: https://github.com/user-attachments/assets/9098d5fb-e886-4047-8a6d-068cfeadd580
**Luck** being processed  as **Learn** and **Bog** being processed as **Browse**: https://github.com/user-attachments/assets/9ecbe92a-37ac-45d6-afe6-2aa7b8fe56b7
Capitalization not mattering for learn, browse, and adopt: https://github.com/user-attachments/assets/d42474af-afaa-4bc6-b41d-0e183df56020

**Comment by ShawnGHB** [comment]
I've gone in and changed all cases of StartsWith() to Equals(). Good Catch

**Comment by ShawnGHB** [comment]
Closing
